// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Security.Models;

public partial class ApplicationDbContext : DbContext
{
    public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Password> Passwords { get; set; }

    public virtual DbSet<PwnedPassword> PwnedPasswords { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Password>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Password__3214EC07FE850A01");

            entity.Property(e => e.Password1)
                .HasMaxLength(200)
                .HasColumnName("Password");
        });

        modelBuilder.Entity<PwnedPassword>(entity =>
        {
            entity.HasKey(e => e.Passwords).HasName("PK_pwned_passwords_passwords");

            entity.ToTable("pwned_passwords");

            entity.Property(e => e.Passwords)
                .HasMaxLength(20)
                .IsFixedLength()
                .HasColumnName("passwords");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}