// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Security.Models;

public partial class Password
{
    public int Id { get; set; }

    public string Password1 { get; set; }
}