// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Security.Models;

#nullable disable

namespace securite.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251213194252_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Security.Models.Password", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Password");

                    b.HasKey("Id")
                        .HasName("PK__Password__3214EC07FE850A01");

                    b.ToTable("Passwords");
                });

            //modelBuilder.Entity("Security.Models.PwnedPassword", b =>
            //    {
            //        b.Property<byte[]>("Passwords")
            //            .HasMaxLength(20)
            //            .HasColumnType("binary(20)")
            //            .HasColumnName("passwords")
            //            .IsFixedLength();

            //        b.HasKey("Passwords")
            //            .HasName("PK_pwned_passwords_passwords");

            //        b.ToTable("pwned_passwords", (string)null);
            //    });
#pragma warning restore 612, 618
        }
    }
}
